package com.material.pmsa;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.material.pmsa.cardboard.CardBoard;
import com.material.pmsa.cardboard.CardBoardRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private CardBoardRepository cardBoardRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @PostMapping(path = "/add-cardboard")
    public @ResponseBody String addNewCardboard(
        @RequestParam(required = false) String companySize, 
        @RequestParam(required = false) Integer shippingSize, 
        @RequestParam(required = false) Integer cardboardNo, 
        @RequestParam(required = false) String cardboardType, 
        @RequestParam(required = false) Integer lengthOuter, 
        @RequestParam(required = false) Integer widthOuter, 
        @RequestParam(required = false) Integer heightOuter, 
        @RequestParam(required = false) Integer dimensionalWeight, 
        @RequestParam(required = false) String remark
    ) {
        CardBoard n = new CardBoard();
        n.setCompanySize(companySize);
        n.setShippingSize(shippingSize);
        n.setCardBoardNo(cardboardNo);
        n.setCardboardType(cardboardType);
        n.setLengthOuter(lengthOuter);
        n.setWidthOuter(widthOuter);
        n.setHeightOuter(heightOuter);
        n.setDimensionalWeight(dimensionalWeight);
        n.setRemark(remark);
        cardBoardRepository.save(n);
        return "abc";
    }
}
